In [2]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline
import random

# parameters
gridSize = 4
states_terminal = [[0,0], [gridSize-1, gridSize-1]]
valid_actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
gamma = 0.1 # discount rate
currentReward = -1
numIterations = 100
alpha = 0.1 #exploration factor

# initialization
Q = np.zeros((gridSize *gridSize, len(valid_actions)))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]

Populating the interactive namespace from numpy and matplotlib


C:\Users\33789\anaconda3\lib\site-packages\IPython\core\magics\pylab.py:159: UserWarning: pylab import has clobbered these variables: ['gamma']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


In [3]:
def generateInitialState():
    #generate a random initial state
    #high i sexclusive and low is inclusive 
    x = np.random.randint(low= 0, high = 4)
    y = np.random.randint(low= 0, high = 4)
    initialState= [x, y]
    return initialState

def generateNextAction():
    #generate a random action from the valid set of actions
    a = np.random.randint(low = 0, high = 4 )
    nextAction = valid_actions[a]
    return nextAction

# define the transition function from a given state and action
def getNextState(state, action):
    currentReward = -1
    #define what happens when reaching a terminal state
    # +1 if in final state, -1 if lost
    if state in states_terminal:
        currentReward = 0
        return currentReward, state
    # here you should complete this step, the transition step
    nextState = [sum(x) for x in zip(*[state, action])]
   
    # if the agent reaches a wall 
    if -1 in nextState or gridSize in nextState:
        nextState = state
    
    return currentReward, nextState

In [7]:
for it in range(numIterations):
    currentState = generateInitialState()
    
    
    while True:
        currentAction = generateNextAction()
        reward, nextState = getNextState(currentState, currentAction)
        
        #complete the stop action if the agent reached the goal state
        if nextState in states_terminal or currentState in states_terminal: 
            break 
       
        nextAction = generateNextAction()
        
        #update the Q-value function Q
        Q[state_index(currentState), action_index(currentAction)] = (1-alpha)* Q[state_index(currentState), action_index(currentAction)] + alpha*(reward + gamma* Q[state_index(nextState),action_index(nextAction) ] )
        
        #assign as current state the next state
        currentState = nextState
        currentAction = nextAction 

In [6]:
def state_index(state):
    i = state[0] * 4 + state[1]
    #print(i)
    return i

def action_index(action): 
    for i in range(len(valid_actions)):
        if valid_actions[i] == action: 
            #print(i)
            return i 

In [23]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.91248701, -0.9348347 , -0.95874805,  0.        ],
       [-1.07507718, -1.04050178, -1.05774833, -1.00834002],
       [-1.05934537, -1.02700071, -1.02650723, -1.06568754],
       [ 0.        , -1.02527133, -1.02938299, -0.98577783],
       [-0.94325391, -1.08797284, -0.9904802 , -1.00183951],
       [-1.06387133, -1.06122723, -0.95831574, -1.01574169],
       [-0.96931177, -1.01753282, -1.0605515 , -1.03219883],
       [-1.07894667, -1.07021707, -1.06195705, -1.07482901],
       [-1.03501575, -1.07085438, -1.07774377, -1.09733713],
       [-1.03295778, -1.0251814 , -1.04001559, -1.06995168],
       [-1.01411552,  0.        , -0.96595072, -1.04052065],
       [-1.06871466, -1.09857131, -1.09674308, -1.06796582],
       [-1.07910705, -1.07384916, -1.06182492, -1.09330465],
       [-0.98017274, -0.96452106,  0.        , -1.05592738],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [13]:
gamma = 0.5 
alpha = 0.1

In [15]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.43519385, -1.60957448, -1.69423647,  0.        ],
       [-1.72237055, -1.83582646, -1.85366487, -1.41165517],
       [-1.82105669, -1.79115921, -1.83432971, -1.78855083],
       [ 0.        , -1.65343305, -1.65902442, -1.53590636],
       [-1.51142932, -1.76634454, -1.80230709, -1.51049587],
       [-1.80662739, -1.76325476, -1.81431067, -1.77132221],
       [-1.82261137, -1.57014706, -1.81431526, -1.82309353],
       [-1.45421025, -1.79993988, -1.75513472, -1.68693808],
       [-1.70016213, -1.62668053, -1.7681616 , -1.72795535],
       [-1.82330026, -1.61868971, -1.52952298, -1.71964981],
       [-1.76219041,  0.        , -1.50607687, -1.69192273],
       [-1.72805765, -1.74396254, -1.6320347 , -1.79183576],
       [-1.66575061, -1.53546764, -1.36923961, -1.75645077],
       [-1.61218045, -1.2485244 ,  0.        , -1.57378078],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [16]:
gamma =0.1 
alpha = 0.5 

In [19]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.04859434, -1.11033137, -1.11099404,  0.        ],
       [-1.10949744, -1.11107551, -1.11110551, -1.09687918],
       [-1.11110598, -1.11109201, -1.11109464, -1.11106913],
       [ 0.        , -1.11073034, -1.1104604 , -1.11102965],
       [-1.10676923, -1.11106264, -1.11107506, -1.10618633],
       [-1.10825695, -1.11095211, -1.11080231, -1.11072869],
       [-1.11110233, -1.09642679, -1.11098295, -1.1110574 ],
       [-1.10994602, -1.11110628, -1.11101268, -1.11016695],
       [-1.11082106, -1.11107972, -1.11011137, -1.11079217],
       [-1.11096944, -1.10439868, -1.10994348, -1.11106064],
       [-1.10929196,  0.        , -1.09671354, -1.11056428],
       [-1.1101683 , -1.11107146, -1.11108103, -1.11110455],
       [-1.11090004, -1.11086105, -1.05439979, -1.11109961],
       [-1.10864446, -1.05158442,  0.        , -1.11108748],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [8]:
gamma = 0.1 
alpha = 1.0 

In [9]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96523339, -0.9543251 , -1.01683519,  0.        ],
       [-1.07896748, -1.04567515, -0.96863994, -1.04394254],
       [-1.00818952, -1.00623667, -1.05675529, -1.03631013],
       [ 0.        , -0.93738172, -0.90884903, -0.9121636 ],
       [-1.02247685, -1.07541011, -1.05728714, -1.01884031],
       [-1.01787449, -1.06080468, -1.02044361, -1.09277144],
       [-1.01816689, -0.91725318, -0.9924279 , -1.05662003],
       [-0.99798539, -1.06001247, -1.06229239, -1.05449639],
       [-1.06810616, -1.09124325, -1.07407086, -1.01859688],
       [-1.07225926, -1.03690327, -1.00278275, -1.06275181],
       [-0.97846466,  0.        , -0.93086377, -0.90318342],
       [-1.08140459, -1.10413377, -1.08937779, -1.102553  ],
       [-1.06391444, -1.09560987, -1.06769506, -1.09358987],
       [-1.04677153, -1.03893837,  0.        , -1.04378286],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [10]:
gamma = 1.0 
alpha = 0.1

In [11]:
Q


array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96523339, -0.9543251 , -1.01683519,  0.        ],
       [-1.07896748, -1.04567515, -0.96863994, -1.04394254],
       [-1.00818952, -1.00623667, -1.05675529, -1.03631013],
       [ 0.        , -0.93738172, -0.90884903, -0.9121636 ],
       [-1.02247685, -1.07541011, -1.05728714, -1.01884031],
       [-1.01787449, -1.06080468, -1.02044361, -1.09277144],
       [-1.01816689, -0.91725318, -0.9924279 , -1.05662003],
       [-0.99798539, -1.06001247, -1.06229239, -1.05449639],
       [-1.06810616, -1.09124325, -1.07407086, -1.01859688],
       [-1.07225926, -1.03690327, -1.00278275, -1.06275181],
       [-0.97846466,  0.        , -0.93086377, -0.90318342],
       [-1.08140459, -1.10413377, -1.08937779, -1.102553  ],
       [-1.06391444, -1.09560987, -1.06769506, -1.09358987],
       [-1.04677153, -1.03893837,  0.        , -1.04378286],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [12]:
gamma = 1.0 
alpha = 0.5 

In [13]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96523339, -0.9543251 , -1.01683519,  0.        ],
       [-1.07896748, -1.04567515, -0.96863994, -1.04394254],
       [-1.00818952, -1.00623667, -1.05675529, -1.03631013],
       [ 0.        , -0.93738172, -0.90884903, -0.9121636 ],
       [-1.02247685, -1.07541011, -1.05728714, -1.01884031],
       [-1.01787449, -1.06080468, -1.02044361, -1.09277144],
       [-1.01816689, -0.91725318, -0.9924279 , -1.05662003],
       [-0.99798539, -1.06001247, -1.06229239, -1.05449639],
       [-1.06810616, -1.09124325, -1.07407086, -1.01859688],
       [-1.07225926, -1.03690327, -1.00278275, -1.06275181],
       [-0.97846466,  0.        , -0.93086377, -0.90318342],
       [-1.08140459, -1.10413377, -1.08937779, -1.102553  ],
       [-1.06391444, -1.09560987, -1.06769506, -1.09358987],
       [-1.04677153, -1.03893837,  0.        , -1.04378286],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [14]:
alpha = 1.0 
gamma = 0.5

In [15]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96523339, -0.9543251 , -1.01683519,  0.        ],
       [-1.07896748, -1.04567515, -0.96863994, -1.04394254],
       [-1.00818952, -1.00623667, -1.05675529, -1.03631013],
       [ 0.        , -0.93738172, -0.90884903, -0.9121636 ],
       [-1.02247685, -1.07541011, -1.05728714, -1.01884031],
       [-1.01787449, -1.06080468, -1.02044361, -1.09277144],
       [-1.01816689, -0.91725318, -0.9924279 , -1.05662003],
       [-0.99798539, -1.06001247, -1.06229239, -1.05449639],
       [-1.06810616, -1.09124325, -1.07407086, -1.01859688],
       [-1.07225926, -1.03690327, -1.00278275, -1.06275181],
       [-0.97846466,  0.        , -0.93086377, -0.90318342],
       [-1.08140459, -1.10413377, -1.08937779, -1.102553  ],
       [-1.06391444, -1.09560987, -1.06769506, -1.09358987],
       [-1.04677153, -1.03893837,  0.        , -1.04378286],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [16]:
alpha = 1.0 
gamma = 1.0

In [17]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96523339, -0.9543251 , -1.01683519,  0.        ],
       [-1.07896748, -1.04567515, -0.96863994, -1.04394254],
       [-1.00818952, -1.00623667, -1.05675529, -1.03631013],
       [ 0.        , -0.93738172, -0.90884903, -0.9121636 ],
       [-1.02247685, -1.07541011, -1.05728714, -1.01884031],
       [-1.01787449, -1.06080468, -1.02044361, -1.09277144],
       [-1.01816689, -0.91725318, -0.9924279 , -1.05662003],
       [-0.99798539, -1.06001247, -1.06229239, -1.05449639],
       [-1.06810616, -1.09124325, -1.07407086, -1.01859688],
       [-1.07225926, -1.03690327, -1.00278275, -1.06275181],
       [-0.97846466,  0.        , -0.93086377, -0.90318342],
       [-1.08140459, -1.10413377, -1.08937779, -1.102553  ],
       [-1.06391444, -1.09560987, -1.06769506, -1.09358987],
       [-1.04677153, -1.03893837,  0.        , -1.04378286],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [18]:
alpha = 0.01
gamma = 0.9

In [19]:
Q

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96523339, -0.9543251 , -1.01683519,  0.        ],
       [-1.07896748, -1.04567515, -0.96863994, -1.04394254],
       [-1.00818952, -1.00623667, -1.05675529, -1.03631013],
       [ 0.        , -0.93738172, -0.90884903, -0.9121636 ],
       [-1.02247685, -1.07541011, -1.05728714, -1.01884031],
       [-1.01787449, -1.06080468, -1.02044361, -1.09277144],
       [-1.01816689, -0.91725318, -0.9924279 , -1.05662003],
       [-0.99798539, -1.06001247, -1.06229239, -1.05449639],
       [-1.06810616, -1.09124325, -1.07407086, -1.01859688],
       [-1.07225926, -1.03690327, -1.00278275, -1.06275181],
       [-0.97846466,  0.        , -0.93086377, -0.90318342],
       [-1.08140459, -1.10413377, -1.08937779, -1.102553  ],
       [-1.06391444, -1.09560987, -1.06769506, -1.09358987],
       [-1.04677153, -1.03893837,  0.        , -1.04378286],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])